### ISSUE TITLE
No default jsDelivr CDN file set

### ISSUE THREAD

**Issue by SamHamou** [aasaam/noto-font#2]
[This package](https://www.jsdelivr.com/package/npm/@aasaam/noto-font) doesn't have a [default file](https://www.jsdelivr.com/features#publishing-packages) set. You can set it via `jsdelivr`, `browser`, or `main` field in `package.json`

**Comment by mhf-ir** [comment]
I will add this feature but you can use via:
https://gitcdn.xyz/repo/aasaam/noto-font/master/dist/font-face.css

But it's already exists: https://cdn.jsdelivr.net/npm/@aasaam/noto-font/dist/font-face.min.css
